version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: ms-user
    ports:
      - "5961:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms-user-db